sequentially assign GA to courses
anderscc/CSC750_Project pull request #33
Opened 2022-11-05 21:37 UTC by GodwinEkuma

2022-11-06 23:26 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +        unique_labs = {}
Creating a dictionary for unique labs.

2022-11-06 23:41 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            if lab.get_labCode() in unique_labs:
If lab code is in unique labs, we attend it to the dictionary.

2022-11-06 23:44 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +        gata_course_counter = 0
Counter variable for courses.

2022-11-06 23:44 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            gata = GAList[gata_course_counter]
Assign GAs Iteratively.

2022-11-06 23:44 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            if (len(GAList) - 1) == gata_course_counter:
If we go out of bounds for the list, initialize it back to 0, if not, add 1.

2022-11-06 23:45 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +        gata_lab_counter = 0
Counter for Labs.

2022-11-06 23:45 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            gata = TAList[gata_lab_counter]
Assign TAs iteratively.

2022-11-06 23:45 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            if (len(GAList) - 1) == gata_lab_counter:
If we go out of bounds for the TAList, initialize back to 0. If not, add 1.

2022-11-06 23:46 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +        for cur_lab in unique_labs:
Go through unique labs and assign TAs to labs taught by faculty as well as TA taught lab.

2022-11-06 23:47 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +            if (len(GAList) - 1) == gata_lab_counter:
I'm requesting changes on this comment because we should be checking if we are out of bounds of TAList and not GAList.

2022-11-06 23:47 UTC, Caleb7621-java requested changes, later dismissed
On line 388, change GAList to be TAList.

2022-11-10 02:28 UTC, zhao926 requested changes

2022-11-10 02:28 UTC, zhao926 commented on GeneticAlgorithm.py
> +            newCourseAssignment.set_meetingTime(cur_lab.get_meetTimes())
This line causes an error: AttributeError: 'str' object has no attribute 'get_meetTimes'

2022-11-11 20:36 UTC, merged