i have created a class to get the data from the database
anderscc/CSC750_Project pull request #41
Opened 2022-11-28 02:40 UTC by Olubiggy

2022-11-28 03:27 UTC, anderscc commented
Hey, @Olubiggy there seem to be some merge conflicts with your branch.

2022-11-28 03:45 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +from django.db import models
We should not be importing the models into the GeneticAlgorithm.py file.

2022-11-28 03:45 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +class Getters():
Is this the best way of getting data from the database? We should be making an API call and selecting data given a specific Semester and Year.

2022-11-28 03:46 UTC, Caleb7621-java requested changes
See line comments.

2022-11-28 03:47 UTC, Caleb7621-java commented on GeneticAlgorithm.py
> +    def __init__(self, get_gata, get_courses, get_labs):
All of this should be implemented within the Data class.

2022-11-28 03:47 UTC, Caleb7621-java requested changes
Changes should be made within Data class for pulling data into Algorithm.

2022-12-01 23:51 UTC, Olubiggy commented
i have done this task again

2022-12-01 23:51 UTC, closed without merging